// Gift metadata for the Spiritual Gifts report. Keyed by letter A–Y.
// Scoring itself uses the DB (items.gift_letter); this is display content only.

export const GIFTS = {
  A: { name: "Prophecy", def: "The special ability to receive and communicate an immediate message of God to His people through a divinely anointed utterance.", refs: "Luke 7:26 · Acts 15:32 · Acts 21:9-11 · Romans 12:6 · 1 Cor 12:10, 28 · Eph 4:11-14", roles: "Preaching and teaching ministries, prayer and intercession teams, spiritual advisory roles, prophetic worship, and ministry leadership.", develop: "Spend regular time in prayer and Scripture, learning to discern God's voice. Practice speaking encouragement in safe, accountable settings, and submit what you sense to mature believers for confirmation." },
  B: { name: "Pastor", def: "The special ability to assume a long-term personal responsibility for the spiritual welfare of a group of believers.", refs: "John 10:1-18 · Eph 4:11-14 · 1 Tim 3:1-7 · 1 Pet 5:1-3", roles: "Lead and associate pastors, small group leaders, chaplains, or mentors in discipleship ministries.", develop: "Invest in consistent, personal relationships with those you lead. Study the life of Jesus as the Good Shepherd. Seek training in counseling, leadership, and conflict resolution." },
  C: { name: "Teaching", def: "The special ability to communicate biblical truth in such a way that others will learn and grow.", refs: "Acts 18:24-28 · Acts 20:20-21 · Romans 12:7 · 1 Cor 12:28 · Eph 4:11-14", roles: "Bible study leaders, Sunday school teachers, discipleship instructors, ministry trainers, curriculum writers.", develop: "Deepen your personal study of Scripture and learn to communicate clearly. Practice teaching in small settings and ask for feedback." },
  D: { name: "Wisdom", def: "The special ability to see situations from God's perspective and offer practical, Spirit-led solutions that align with His will.", refs: "Acts 6:3, 10 · 1 Cor 2:1-13 · 1 Cor 12:8 · James 1:5-6 · 2 Pet 3:15-16", roles: "Elders, counselors, leadership advisors, conflict mediators, and decision-making team members.", develop: "Make prayer and Scripture your daily foundation, especially Proverbs and James. Seek counsel from mature believers." },
  E: { name: "Knowledge", def: "The special ability to discover, analyze, and clarify information and ideas pertinent to the well-being of the Body.", refs: "Acts 5:1-11 · 1 Cor 2:14 · 1 Cor 12:8 · 2 Cor 11:6 · Col 2:2-3", roles: "Bible teachers, researchers, apologists, curriculum developers, theological advisors.", develop: "Commit to a lifestyle of study, in Scripture and solid resources. Share insights in ways that equip others. Stay teachable." },
  F: { name: "Exhortation", def: "The special ability to minister words of comfort, encouragement, and counsel so others feel helped and healed.", refs: "Acts 14:22 · Romans 12:8 · 1 Tim 4:13 · Heb 10:25", roles: "Counseling, discipleship, mentoring, preaching, small group leadership, recovery and care ministries.", develop: "Stay rooted in Scripture so your encouragement is biblical and balanced. Ask trusted leaders for feedback on tone and clarity." },
  G: { name: "Discerning of Spirits", def: "The special ability to know with assurance whether behavior purported to be of God is in reality divine, human, or Satanic.", refs: "Matt 16:21-23 · Acts 5:1-11 · Acts 16:16-18 · 1 Cor 12:10 · 1 John 4:1-6", roles: "Prayer and intercession teams, pastoral leadership, deliverance and freedom ministries, counseling.", develop: "Pursue a close walk with God and saturate your mind with Scripture. Practice testing impressions with the Bible and wise counsel." },
  H: { name: "Giving", def: "The special ability to contribute material resources to the work of the Lord with liberality and cheerfulness.", refs: "Mark 12:41-44 · Romans 12:8 · 2 Cor 8:1-7 · 2 Cor 9:2-8", roles: "Key supporters of missions, stewardship campaign leaders, benevolence organizers, mentors in generosity.", develop: "Manage finances with integrity and margin so you can give freely. Seek accountability to keep motives pure." },
  I: { name: "Helps", def: "The special ability to invest your talents in the ministry of others, enabling them to increase their own effectiveness.", refs: "Mark 15:40-41 · Luke 8:2-3 · Acts 9:36 · Romans 16:1-2 · 1 Cor 12:28", roles: "Event setup, administrative support, volunteer coordination, hospitality, tech and facilities teams, logistics.", develop: "Be proactive in offering assistance and finish tasks with excellence. Keep a servant's heart and protect unity." },
  J: { name: "Mercy", def: "The special ability to feel deep compassion for those who suffer and respond with practical acts of care that bring comfort and hope.", refs: "Matt 20:29-34 · Matt 25:34-40 · Mark 9:41 · Luke 10:33-35 · Acts 16:33-34 · Romans 12:8", roles: "Care and visitation ministries, crisis response, benevolence and outreach, counseling support, prison and hospital ministry.", develop: "Take steady, small steps of compassionate service. Set healthy boundaries and practice self-care so you can serve long-term." },
  K: { name: "Missionary", def: "The special ability to minister your other spiritual gifts effectively in a second culture, crossing cultural and language boundaries for Christ.", refs: "Acts 8:4 · Acts 13:2-3 · Acts 22:21 · Romans 10:15 · 1 Cor 9:19-23", roles: "Foreign missionaries, cross-cultural church planters, short-term mission leaders, outreach coordinators.", develop: "Immerse yourself in God's heart for the nations. Volunteer for cross-cultural outreach locally. Learn cultural sensitivity and adaptability." },
  L: { name: "Evangelist", def: "The special ability to share the gospel with unbelievers in a way that leads them to repent, believe, and follow Christ.", refs: "Acts 8:5-6 · Acts 8:26-40 · Acts 14:21 · Acts 21:8 · Eph 4:11-14 · 2 Tim 4:5", roles: "Outreach ministries, personal witnessing, large evangelistic events, street ministry, online evangelism.", develop: "Know the gospel thoroughly and practice sharing it clearly. Learn to tell your testimony compellingly. Pray for divine appointments." },
  M: { name: "Hospitality", def: "The special ability to make others feel welcomed and cared for, often through food, lodging, or a warm environment where relationships grow.", refs: "Acts 16:14-15 · Romans 12:9-13 · Romans 16:23 · Heb 13:1-2 · 1 Pet 4:9", roles: "Greeters, small group hosts, fellowship meal organizers, event planners, housing for missionaries and guests.", develop: "Intentionally create welcoming environments. Offer your time and resources to meet practical needs. See strangers as opportunities for ministry." },
  N: { name: "Faith", def: "The special ability to trust God's promises and purposes with extraordinary confidence, even in the face of obstacles or uncertainty.", refs: "Acts 11:22-24 · Acts 27:21-25 · Romans 4:18-21 · 1 Cor 12:9 · Heb 11", roles: "Intercessors, vision-casters, ministry pioneers, church planters, encouragers during change.", develop: "Focus on God's character and track record. Step out in obedience in small ways and watch God provide. Surround yourself with faith-filled believers." },
  O: { name: "Leadership", def: "The special ability to set God-honoring goals, inspire people to pursue them, and guide a group toward accomplishing them in unity.", refs: "Luke 9:51 · Acts 7:10 · Acts 15:7-11 · Romans 12:8 · 1 Tim 5:17 · Heb 13:17", roles: "Pastors, elders, ministry directors, project leaders, team coordinators.", develop: "Seek God's wisdom before decisions and lead with humility. Grow in communication and organizational skills. Invite feedback." },
  P: { name: "Administration", def: "The special ability to organize people, resources, and processes, turning vision into actionable steps completed with excellence.", refs: "Luke 14:28-30 · Acts 6:1-7 · Acts 27:11 · 1 Cor 12:28 · Titus 1:5", roles: "Ministry coordinators, event planners, project managers, church administrators.", develop: "Refine your organizational skills and learn proven planning methods. Prioritize according to God's purposes, not just efficiency." },
  Q: { name: "Miracles", def: "The special ability to serve as a vessel through whom God performs supernatural acts that defy natural explanation and bring Him glory.", refs: "Acts 9:36-42 · Acts 19:11-20 · Acts 20:7-12 · Romans 15:18-19 · 1 Cor 12:10, 28 · 2 Cor 12:12", roles: "Healing services, evangelistic events, intercessory prayer teams, frontline ministries.", develop: "Cultivate a life of prayer, obedience, and deep trust in God's ability to do the impossible. Step out boldly when prompted." },
  R: { name: "Healing", def: "The special ability to serve as a channel through whom God restores physical, emotional, or spiritual health apart from natural means.", refs: "Acts 3:1-10 · Acts 5:12-16 · Acts 9:32-35 · Acts 28:7-10 · 1 Cor 12:9, 28 · James 5:14-16", roles: "Prayer and altar ministry, hospital visitation, healing services, outreach events.", develop: "Study the healing ministry of Jesus and the apostles. Pray regularly for the sick. Give all glory to God and show compassion to those still waiting." },
  S: { name: "Tongues", def: "The special ability to speak to God in a language unknown to the speaker, as a personal prayer language or a public message when interpreted.", refs: "Mark 16:17 · Acts 2:1-13 · Acts 10:44-46 · Acts 19:1-7 · 1 Cor 12:10, 28 · 1 Cor 14:13-19", roles: "Intercessory prayer, prophetic ministry, public worship where God gives a message in tongues.", develop: "Spend time in prayer asking the Holy Spirit to deepen your connection with God. Study Scripture to understand its purpose and biblical use." },
  T: { name: "Interpretation", def: "The special ability to make known the meaning of a message given in tongues, so the church is edified.", refs: "1 Cor 12:10, 30 · 1 Cor 14:13 · 1 Cor 14:26-28", roles: "Serving alongside those with the gift of tongues in public worship, prophetic gatherings, or prayer meetings.", develop: "Spend time in worship and prayer learning to recognize the Spirit's voice. Test impressions with Scripture. Submit what you sense to leadership." },
  U: { name: "Voluntary Poverty", def: "The special ability to joyfully renounce material comfort, living at or near the level of those served to devote resources fully to God's work.", refs: "Acts 2:44-45 · Acts 4:34-37 · 1 Cor 13:1-3 · 2 Cor 6:10 · 2 Cor 8:9", roles: "Missionaries, church planters, urban ministers, nonprofit workers, compassion-based ministries.", develop: "Pray for contentment with basic needs. Practice simplifying your life and redirecting resources toward ministry." },
  V: { name: "Singleness", def: "The special ability to remain single without undue struggle, using singleness as an opportunity to serve God more freely and fully.", refs: "Matt 19:10-12 · 1 Cor 7:7-8 · 1 Cor 7:32-35", roles: "Missionary work, pastoral ministry, mentoring, roles where flexibility and full-time dedication help.", develop: "Cultivate a deep relationship with God, maintain healthy friendships, and focus on purposeful service." },
  W: { name: "Intercession", def: "The special ability to pray for extended periods, consistently seeing frequent and specific answers, carrying a burden for people and situations.", refs: "Luke 22:41-44 · Acts 12:12 · Col 1:9-12 · Col 4:12-13 · 1 Tim 2:1-2 · James 5:14-16", roles: "Prayer teams, intercessory group leaders, supporting missionaries and pastors in prayer.", develop: "Set aside consistent time for focused prayer. Keep a prayer journal to track requests and answers." },
  X: { name: "Exorcism", def: "The special ability to cast out demons and evil spirits through the authority of Jesus Christ, bringing deliverance and freedom.", refs: "Matt 12:22-32 · Luke 10:17-20 · Acts 8:5-8 · Acts 16:16-18 · Mark 16:17", roles: "Deliverance ministries, pastoral counseling, missionary work in spiritually resistant areas.", develop: "Deepen your understanding of Scripture regarding spiritual warfare. Serve under mature spiritual covering." },
  Y: { name: "Service", def: "The special ability to identify and meet practical needs, using available resources to help accomplish God's work.", refs: "Acts 6:1-7 · Romans 12:7 · Galatians 6:2, 10 · 2 Tim 1:16-18 · Titus 3:14", roles: "Volunteer coordination, maintenance, setup and teardown, outreach preparation.", develop: "Look for unmet needs and step in without waiting to be asked. Serve with excellence and joy in both seen and unseen roles." },
};

export function ordinal(n) {
  const s = ["th", "st", "nd", "rd"], v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}
